#!/bin/sh
# Adapted from
# - Madnuttah's unbound.sh (https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/entrypoint)

DISABLE_SET_PERMS=${DISABLE_SET_PERMS:-false}
UNBOUND_UID=${UNBOUND_UID:-1001}
UNBOUND_GID=${UNBOUND_GID:-1001}
PORT=${HEALTHCHECK_PORT:-5335}
unbound_root=/usr/local/unbound

# 1. Set permission
disable_set_perms=$DISABLE_SET_PERMS
if $disable_set_perms; then
  command="exec"
else
  set_perms=0
  if [ $(id -u _unbound) -ne $UNBOUND_UID ]; then
    usermod -o -u $UNBOUND_UID _unbound
    set_perms=1
  fi
  if [ $(id -g _unbound) -ne $UNBOUND_GID ]; then
    groupmod -o -g $UNBOUND_GID _unbound
    set_perms=1
  fi
  if [ $set_perms -eq 1 ]; then
    chown -R $UNBOUND_UID:$UNBOUND_GID $unbound_root >/dev/null 2>&1
  fi
  command="exec su-exec $UNBOUND_UID:$UNBOUND_GID"
fi

# 2. Tune unbound.conf
# Populate unbound.conf as function of memory and CPU
reserved=12582912
availableMemory=$((1024 * $( (grep MemAvailable /proc/meminfo || grep MemTotal /proc/meminfo) | sed 's/[^0-9]//g' ) ))
memoryLimit=$availableMemory
[ -r /sys/fs/cgroup/memory/memory.limit_in_bytes ] && memoryLimit=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes | sed 's/[^0-9]//g')
[[ ! -z $memoryLimit && $memoryLimit -gt 0 && $memoryLimit -lt $availableMemory ]] && availableMemory=$memoryLimit
if [ $availableMemory -le $(($reserved * 2)) ]; then
    echo "Not enough memory" >&2
    exit 1
fi
availableMemory=$(($availableMemory - $reserved))
rr_cache_size=$(($availableMemory / 3))

# Use roughly twice as much rrset cache memory as msg cache memory
msg_cache_size=$(($rr_cache_size / 2))
nproc=$(nproc)
export nproc
if [ "$nproc" -gt 1 ];
then
    threads=$((nproc - 1))
    # Calculate base 2 log of the number of processors
    nproc_log=$(perl -e 'printf "%5.5f\n", log($ENV{nproc})/log(2);')

    # Round the logarithm to an integer
    rounded_nproc_log="$(printf '%.*f\n' 0 "$nproc_log")"

    # Set *-slabs to a power of 2 close to the num-threads value.
    # This reduces lock contention.
    slabs=$(( 2 ** rounded_nproc_log ))
else
    threads=1
    slabs=4
fi

if [ -f $unbound_root/unbound.conf ]; then
    sed -i -e "s/@MSG_CACHE_SIZE@/${msg_cache_size}/" \
       -e "s/@RR_CACHE_SIZE@/${rr_cache_size}/" \
       -e "s/@THREADS@/${threads}/" \
       -e "s/@SLABS@/${slabs}/" \
       -e "s/@PORT@/${PORT}/" $unbound_root/unbound.conf
fi

# 3. Start unbound
$command $unbound_root/sbin/unbound.sh $disable_set_perms