name: CD 91 - Test Docker Login

on:
  # push:
  #   branches: master
  workflow_dispatch:

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout source
      #   uses: actions/checkout@v5
      #   with:
      #     persist-credentials: false
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    