# 1 - Daily check of upstream release for Unbound and OpenSSL
name: CD Unbound and OpenSSL upstream release check

on:
  schedule:
    - cron: '0 17 * * mon-fri'
  workflow_dispatch:

jobs:
  unbound-update:
    runs-on: ubuntu-latest
              
    steps:
      - name: Get versions
        id: GET_VERSIONS
        run: |
            # Unbound Release
            BOOL="$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases | jq '.[0] | .prerelease')"
            if $BOOL; then
                echo "Pre-release, skipping"
                exit 1
            else
                echo UNBOUND_VERSION="$(curl -s https://api.github.com/repos/NLnetLabs/unbound/releases | jq '.[0] | .name' -r | grep -Eo '([0-9]+)(\.?[0-9]+)*' | head -1)" >> $GITHUB_OUTPUT
            fi

            # OpenSSL Release, skipping prerelease
            BOOL="$(curl -s https://api.github.com/repos/openssl/openssl/releases | jq '.[0] | .prerelease')"
            if $BOOL; then
                echo "Pre-release, skipping"
                exit 1
            else
                echo OPENSSL_VERSION="$(curl -s https://api.github.com/repos/openssl/openssl/releases | jq '.[0] | .name' -r | grep -Eo '([0-9]+)(\.?[0-9]+)*' | head -1)" >> $GITHUB_OUTPUT 
            fi

            echo UNBOUND_DOCKER_VERSION="$(curl -s https://raw.githubusercontent.com/megavolts/unbound-docker/refs/heads/main/.current_release | awk '/^UNBOUND_VERSION=/' | cut -d= -f2)" >> $GITHUB_OUTPUT  
            echo OPENSSL_DOCKER_VERSION="$(curl -s https://raw.githubusercontent.com/megavolts/unbound-docker/refs/heads/main/.current_release | awk '/^OPENSSL_VERSION=/' | cut -d= -f2)" >> $GITHUB_OUTPUT  
            echo BUILD_REVISION="$(curl -s https://raw.githubusercontent.com/megavolts/unbound-docker/refs/heads/main/.current_release | awk '/^DOCKER_IMAGE_VERSION=/' | cut -d- -f2)" >> $GITHUB_OUTPUT  

      - name: Is update available
        id: IS_UPDATE_AVAILABLE
        run: |
          if ! [[ "${{ steps.GET_VERSIONS.outputs.UNBOUND_VERSION }}" = "${{ steps.GET_VERSIONS.outputs.UNBOUND_DOCKER_VERSION }}" ]]; then
            echo "Update found for Unbound"
            echo BUILD_REVISION=0 >> $GITHUB_OUTPUT
          elif ! [[ "${{ steps.GET_VERSIONS.outputs.OPENSSL_VERSION }}" = "${{ steps.GET_VERSIONS.outputs.OPENSSL_DOCKER_VERSION }}" ]]; then
            echo "Update found for OpenSSL"
            echo BUILD_REVISION="$(( ${{ steps.GET_VERSIONS.outputs.BUILD_DOCKER_REVISION }}+1 ))" >> $GITHUB_OUTPUT  
          else
            echo "No update found"
            exit 1
          fi 
         
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          
      - name: Import GPG key 
        id: IMPORT_GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
          trust_level: 5

      - name: Push files to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.IMPORT_GPG.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.IMPORT_GPG.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.IMPORT_GPG.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.IMPORT_GPG.outputs.email }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}  
          OPENSSL_VERSION=${{ steps.GET_VERSIONS.outputs.OPENSSL_VERSION }} 
          UNBOUND_VERSION=${{ steps.GET_VERSIONS.outputs.UNBOUND_VERSION }}
          BUILD_REVISION=${{ steps.GET_VERSIONS.outputs.BUILD_REVISION }}
          DOCKER_IMAGE_VERSION=$UNBOUND_VERSION-$BUILD_REVISION
          echo OPENSSL_VERSION=$OPENSSL_VERSION > buildvars
          echo UNBOUND_VERSION=$UNBOUND_VERSION >> buildvars
          echo BUILD_REVISION=$BUILD_REVISION >> buildvars
          git add buildvars
          git commit buildvars -m "Updated buildvars"
          git push origin main
          exit 0
  